-- Таблица MPA рейтингов
CREATE TABLE IF NOT EXISTS mpa (
                                   id INTEGER PRIMARY KEY,
                                   name VARCHAR(10) NOT NULL,
    description VARCHAR(200)
    );

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
                                      id INTEGER PRIMARY KEY,
                                      name VARCHAR(50) NOT NULL
    );

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(100) NOT NULL,
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    mpa_id INTEGER REFERENCES mpa(id)
    );

-- Связь фильмов и жанров (многие-ко-многим)
CREATE TABLE IF NOT EXISTS film_genres (
                                           id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres(id),
    CONSTRAINT film_genre_unique UNIQUE (film_id, genre_id)
    );

-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(50) NOT NULL,
    login VARCHAR(50) NOT NULL,
    name VARCHAR(50),
    birthday DATE
    );

-- Таблица дружбы
CREATE TABLE IF NOT EXISTS friendship (
                                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    status BOOLEAN DEFAULT FALSE,
    CONSTRAINT friendship_unique UNIQUE (user_id, friend_id)
    );

-- Таблица лайков фильмов
CREATE TABLE IF NOT EXISTS film_likes (
                                          film_id INTEGER REFERENCES films(id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );